# Generated by Django 4.0.6 on 2022-09-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_news_options_news_most_important_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='most_important',
            field=models.TextField(max_length=255),
        ),
    ]
