# Generated by Django 4.0.6 on 2022-09-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_news_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='photo',
        ),
    ]
